OSC/ood_core

lib/ood_core/job/adapter.rb
lib/ood_core/job/adapters/slurm.rb
lib/ood_core/job/adapters/torque.rb
spec/job/adapter_spec.rb
spec/job/adapters/slurm_spec.rb
spec/job/adapters/torque_spec.rb

Fixes #12
Also removes keyword args such as `script:` and `id:` as these are always required for the respective methods.

New job adapter API

---

lib/ood_core/acl/adapters/group.rb
lib/ood_core/job/adapters/slurm.rb
lib/ood_core/job/adapters/torque.rb

Set documentation on adapter intializers to private so it keeps it internal.

Set adapter initializers to private in docs

---

CHANGELOG.md
lib/ood_core/job/adapters/lsf/batch.rb
spec/job/adapters/lsf/batch_spec.rb

`bjobs` output 9.1 may include an extra column SLOTS
1. update the bjobs line parsing code to not assume 15 columns but handle a variable number of columns
2. update the bjobs output validation to verity that the output has the expected columns in order, but ignore extra columns
Note:
The current fix has validation that assumes if columns `JOBID USER STAT QUEUE...` appear there will never be new columns before `JOBID` but only after.
This still has the problem that in 8.3 there wasn't a clean way to get the estimated runtime, as there is in 9.1. So the estimated runtime is still current time - start time, and it is accurate only if the job never goes into a suspended state.
For this reason, we should have LSF 9+ users add version: "9.1" to their cluster config.

handle LSF 9.1 bjobs output

---

CHANGELOG.md
lib/ood_core/job/adapter.rb
spec/job/adapter_spec.rb

Fixes #26
Changed it from `#info_where_user` to `#info_where_owner` because we defined it in the `Info` object as `#job_owner`.

Add helper method to filter jobs by owner

---

CHANGELOG.md
lib/ood_core/job/adapters/torque.rb
spec/job/adapters/torque_spec.rb

This can be used in ActiveJobs and possibly iHPC Dashboard for gathering information on nodes/procs requested for jobs while they are in queue. It isn't guaranteed this information will be available though.

Provide node/procs info if available for non-running jobs in Torque

---

lib/ood_core/job/adapters/lsf.rb
lib/ood_core/job/adapters/lsf/batch.rb
spec/job/adapters/lsf/batch_spec.rb
spec/job/adapters/lsf_spec.rb

Implement support for optimized info_where_owner in LSF adapter.
Unfortunately, it doesn't seem that, in at least LSF 8.3, bjobs can accept a list of users as arguments. Either one user or one group or all users.

[WIP] LSF Adpater: info_where_owner optimization

---

lib/ood_core/job/adapters/lsf.rb
lib/ood_core/job/adapters/lsf/batch.rb
spec/job/adapters/lsf/batch_spec.rb

in multi-cluster mode you must set the cluster when using
commands like bjobs and bsub etc. using -m "cluster"
so if cluster attribute is set in the job config, we assume
multi-cluster mode

add basic lsf multi-cluster support

---

lib/ood_core/batch_connect/templates/vnc.rb

`lib/ood_core/batch_connect/templates/vnc.rb` currently tries to call `random 1 9` rather than `random_number 1 9`. The `random` command isn't defined and other places that need random numbers use `random_number`. For example:
```bash
local port=$(random_number "${2:-#{min_port}}" "${3:-#{max_port}}")
```
`random_number` is defined as a helper in `lib/ood_core/batch_connect/template.rb`:
```bash
random_number () {
shuf -i ${1}-${2} -n 1
}
export -f random_number
```

VNC template should use random_number function.

---

CHANGELOG.md
lib/ood_core/batch_connect/template.rb
lib/ood_core/batch_connect/templates/vnc.rb

This sets a default password length of 8 to maintain backwards compatibilty, while providing the ability to override the default in `submit.yml.erb` by setting the key `batch_connect.passwd_size` to a positive non-zero integer value.
```yaml
---
batch_connect:
template: vnc
passwd_size: 16  # <-- optional new stuff
script:
native:
resources:
nodes: "<%= bc_num_slots %><%= node_type %>"
```
Also fixes a bug where some values for the `LANG` environment variable might result in invalid passwords by making the character ranges available to `tr` more explicit.
Addresses #93 and #91.

Password context

---

lib/ood_core/job/adapters/slurm.rb
spec/job/adapters/slurm_spec.rb

Adds fix and test
Since Slurm 18 `squeue` stopped outputting delimiters after `%b`. We are reliant on delimiters, we can work around this issue by moving `%b` to the end of the field list, and rely on Ruby's ordered hashes to leave the entry at the end.
Fixes #99, and is a better solution than #105.

Fix issue with Slurm 18 squeue output format bug

---

lib/ood_core/job/adapter.rb
lib/ood_core/job/adapters/lsf.rb
lib/ood_core/job/adapters/pbspro.rb
spec/job/adapters/lsf_spec.rb
spec/job/adapters/pbspro_spec.rb
spec/job/adapters/sge_spec.rb
spec/job/adapters/slurm_spec.rb
spec/job/adapters/torque_spec.rb

Add boolean indicating whether or not a job adapter supports job arrays.
We might consider a general purpose version of a method like this, for all "features", such as all the submit options on Script and all of the Info attrs.

Add Adapter#supports_job_arrays?

---

lib/ood_core/job/adapters/sge.rb
lib/ood_core/job/adapters/sge/batch.rb
lib/ood_core/job/adapters/sge/helper.rb
spec/job/adapters/sge/helper_spec.rb
spec/job/adapters/sge_spec.rb

By setting `-cwd` we ensure that stdout/stderr are written to the correct place. With GE a script's content does not override command line options to `qsub`. The GE helper attempts to work around the `qsub` limitations by detecting `-wd` and `-cwd` directives in the first 1024 characters and first 20 lines of a script, thus allowing us to be selective about whether we want to force the `-cwd` flag to be set or not.
Tests were written for the helper method. Note as well that `-cwd` became a default option for the `#submit` tests, necessitating its inclusion.

SGE defaults to passing the -cwd flag

---

lib/ood_core/clusters.rb
spec/clusters_spec.rb

Fixes crash when a YAML file in the clusters.d is not readable by the user

Add cluster ACLs based on the cluster config's file permissions

---

lib/ood_core/job/adapter.rb
lib/ood_core/job/adapters/linux_host.rb
lib/ood_core/job/adapters/lsf.rb
lib/ood_core/job/adapters/pbspro.rb
lib/ood_core/job/adapters/sge.rb
lib/ood_core/job/adapters/slurm.rb
lib/ood_core/job/adapters/torque.rb
spec/job/adapter_spec.rb
spec/job/adapters/linux_host_spec.rb
spec/job/adapters/lsf_spec.rb
spec/job/adapters/pbspro_spec.rb
spec/job/adapters/sge_spec.rb
spec/job/adapters/slurm_spec.rb
spec/job/adapters/torque_spec.rb

Adapters which do not support directive_prefix (such as the LinuxHost) are expected to raise JobAdapterError instead of NotImplementedError.
Fixes #161.

Add directive_prefix to all adapters

---

lib/ood_core/job/adapters/lsf/helper.rb
lib/ood_core/job/adapters/pbspro.rb
lib/ood_core/job/adapters/sge/helper.rb
lib/ood_core/job/adapters/slurm.rb
lib/ood_core/job/adapters/torque.rb
lib/ood_core/job/script.rb
spec/job/adapters/lsf/helper_spec.rb
spec/job/adapters/pbspro_spec.rb
spec/job/adapters/sge_spec.rb
spec/job/adapters/slurm_spec.rb
spec/job/adapters/torque_spec.rb
spec/job/script_spec.rb

Copy environment

---

lib/ood_core/batch_connect/template.rb

Clearly most sites don't already have nc installed.  This will actually tell them that it isn't installed.
I was able to test with, commenting out nc and adding the 'notfound' command.
```bash
#nc -w 2 "${host}" "${port}" < /dev/null > /dev/null 2>&1
notfound >/dev/null 2>&1
```

fail fast if nc is not installed and indicate that it isn't installed

---

lib/ood_core.rb
lib/ood_core/cluster.rb
lib/ood_core/clusters.rb
lib/ood_core/invalid_cluster.rb
spec/clusters_spec.rb
spec/fixtures/config/clusters.d/malformed.yml

This can catch Psych::SyntaxError while parsing a malformed cluster definition file and safely traverse empty cluster definitions.  This tries to fix #150 and #178. 
Most uses of Clusters filter off of `allow?` or `custom_allow?` and the InvalidCluster doesn't allow for anything so most (if not all) uses of clusters will filter these types out. 
Right now the only things you can really rely on are the `id` and `metadata.error_msg`.

Catch expections in parsing bad and empty cluster files

---

lib/ood_core/job/adapters/linux_host.rb
spec/job/adapters/linux_host_spec.rb

Active Jobs throws this error.  I tracked it down to the LHA's info_where_owner signature being just a little off.

info_where_owner signature is wrong. owner is not a named parameter

---

lib/ood_core/job/adapters/linux_host/launcher.rb
spec/job/adapters/linux_host/launcher_spec.rb

- commands are written in bash, so the ssh commands are now specifying bash
to support users who have different login shells.
- -l given to pstree for long output becuase without it, it cuts off needed
output.

lha bug fixes

---

lib/ood_core/job/adapters/slurm.rb
lib/ood_core/job/script.rb
spec/job/adapters/slurm_spec.rb

fix SLURM environment setup such that --export=NONE is the default
(as it was before with SBATCH_EXPORT=NONE), job_environment adds
correctly to --export, and copy_environment correctly prefixes with ALL.
comment also left in the code as to why we default to NONE.
Fixes the issues raised in and created by #109 and #158.

fix SLURM env setup

---

lib/ood_core/job/adapters/torque.rb
spec/job/adapters/torque_spec.rb

Fix spaces for envvars in submit.yml.erb

---

lib/ood_core/job/adapters/sge/qstat_xml_j_r_listener.rb
lib/ood_core/job/adapters/sge/qstat_xml_r_listener.rb
spec/job/adapters/sge/batch_spec.rb

Added cpu/mem_usage attributes following gridengine/qstat.xsd

Attributes from qstat command now found under native hash

---

lib/ood_core/job/adapters/linux_host/launcher.rb
lib/ood_core/job/adapters/linux_host/templates/script_wrapper.erb.sh
spec/job/adapters/linux_host/launcher_spec.rb

Fixes #211 
Initially I'd added some complexity to look into the tmux pstree to see if singularity had started, but now I'm just thinking why not just keep the files in the `workdir`?  The `debug` flag won't really do much now, but there's no race condition and it'll mean we can always debug.

Lha timing bug

---

.github/workflows/test.yml
.travis.yml
README.md

replace travis ci with gh actions. This is just testing now, but we should look into publishing the gem automatically too afterwards.

replace travis ci with gh actions

---

lib/ood_core/job/adapters/kubernetes/helper.rb
lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/expected_pod_create.yml
spec/job/adapters/kubernetes/helper_spec.rb

I opted to use easier to read format like `1h5m` rather than just do everything as seconds.  If preferred could just as easily make everything seconds, so 3600 would become `3600s` (`s` suffix).
Also verified `annotations` with no key/value pairs does work.

Support defining pod lifetime for Kubernetes

---

lib/ood_core/job/adapters/kubernetes.rb
lib/ood_core/job/adapters/kubernetes/batch.rb
lib/ood_core/job/adapters/kubernetes/helper.rb
spec/fixtures/output/k8s/ns_prefixed_pod.json
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/job/adapters/kubernetes/batch_spec.rb
spec/job/adapters/kubernetes/helper_spec.rb

With #218 we now need to convert map the namespace back to `info.job_owner` because their not necessarily the same any more.
This also fixes #219 though that's kinda secondary.

Helper namespace

---

.github/workflows/test.yml
ood_core.gemspec

update bundler to v2.1 and update automation to use ruby 2.7.  The GH action also updates to use `ruby/setup-ruby@v1` because it's simpler for a single gem.

update bundler to v2.1 and update automation to use ruby 2.7

---

lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_no_mounts.yml
spec/job/adapters/kubernetes/batch_spec.rb

I found this in AKS testing that the k8s pod template did not correctly populate a 'volumes' section when there are no mounts present.  One only has to checkout the master version of `lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb` and run this added test to verify.

k8s templates bugfix

---

lib/ood_core/job/adapters/kubernetes/batch.rb
lib/ood_core/job/adapters/kubernetes/helper.rb

This came up in #222 I just didn't get a chance to add it there, so it's here.
This references classes with the semi-full module path instead of redefining them.

use the semi-full module path for classes

---

lib/ood_core/job/adapters/kubernetes/resources.rb
lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml

Ensure the Pod YAML has proper security defined in case sites don't use Pod Security Policies or other tools to enforce stricter security.  For OSC these things will be enforced using Kyverno but sites can choose whatever tool they wish to enforce these values are set.  This helps ensure OnDemand is shipping with "secure by default" settings.

Improved Kubernetes pod security

---

lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml

Saw many community Pods and some best practice docs to also set this. Also the Kyverno policies we will apply at OSC will enforce this even if `runAsUser` is set. I'm not 100% certain if `runAsNonRoot` is useless when setting `runAsUser` but figured doesn't hurt to define both.

Also add runAsNonRoot to K8 pod

---

lib/ood_core/job/adapters/kubernetes/batch.rb
lib/ood_core/job/adapters/kubernetes/helper.rb

K8s is currently broken with all sorts of uninitialized constant errors.  So the fix is just to directly use the full module::class name to reference objects.

use full module names in k8s helper classes

---

lib/ood_core/job/adapters/kubernetes/helper.rb
lib/ood_core/job/adapters/kubernetes/resources.rb
lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml
spec/fixtures/output/k8s/pod_yml_subpath_configmap.yml
spec/job/adapters/kubernetes/batch_spec.rb

* Support mounting at subPath
* Support mounting files that might not be defined statically but instead generated in init container
configmap related items from #250

Rework how configmap is defined for several purposes

---

lib/ood_core/job/adapters/kubernetes/batch.rb
lib/ood_core/job/adapters/kubernetes/resources.rb
lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml
spec/fixtures/output/k8s/pod_yml_no_mounts_no_configmaps.yml
spec/job/adapters/kubernetes/batch_spec.rb

Fixes #254 
I opted so that the init configmap mount only happens when you define `init_mount_path`, same for main container and `mount_path`.

Make K8 configmap configuration more intuitive

---

CHANGELOG.md

update changelog for v0.16.0.  I figure we'll bump the minor version to `v0.16.0` because the kubernetes adapter's interface changed slightly for configmaps.

update changelog for v0.16.0

---

CHANGELOG.md
lib/ood_core/version.rb

Simple changelog and version updates for the next release `v1.16.1`.

bump version and update changelog

---

lib/ood_core/job/adapters/kubernetes/batch.rb
lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/job/adapters/kubernetes/batch_spec.rb

Replaces #262, this can be used to select a node by the node's labels which could be used to choose a cluster or to choose a specific kind of GPU when requesting GPUs.

Allow K8 pods to use nodeSelector

---

lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_no_init_container.yml
spec/job/adapters/kubernetes/batch_spec.rb

Noticed that a definition with no init containers defined still had `initContainers` in YAML:
```
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- all
privileged: false
initContainers:
volumes:
```
This didn't seem to break anything, just a bit of clean up.

Kubernetes - avoid empty initContainers definition

---

lib/ood_core/cluster.rb
spec/cluster_spec.rb

Add cluster batch_connect_ssh_allow? function to allow easier access to a new setting:
```
batch_connect:
ssh_allow: <boolean>
```
Needed for https://github.com/OSC/ondemand/issues/1157
Not sure if this is best approach or if better to just add all the logic to OnDemand dashboard app to look for a certain config inside the cluster `batch_connect` settings.

Add cluster batch_connect_ssh_allow? function to allow easier access to a new setting

---

lib/ood_core/cluster.rb
spec/cluster_spec.rb

Based on conversation from https://github.com/OSC/ondemand/pull/1173

Allow cluster batch_connect_ssh_allow? to return nil if not defined

---

lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_no_init_container.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml
spec/fixtures/output/k8s/pod_yml_no_mounts_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_subpath_configmap.yml

This is useful to avoid hardcoding port numbers into batch connect job templates and can also be used to pass the port number to commands launching a container.

Expose pod port as environment variable

---

lib/ood_core/job/adapters/kubernetes/batch.rb
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_no_init_container.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml
spec/fixtures/output/k8s/pod_yml_no_mounts_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_subpath_configmap.yml
spec/job/adapters/kubernetes/batch_spec.rb

Fixes #283
Added test to validate someone can still override KUBECONFIG if they define it.

Default to setting KUBECONFIG=/dev/null

---

lib/ood_core/job/adapters/kubernetes/helper.rb
lib/ood_core/job/adapters/kubernetes/resources.rb
lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_no_init_container.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml
spec/fixtures/output/k8s/pod_yml_no_mounts_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_subpath_configmap.yml
spec/job/adapters/kubernetes/batch_spec.rb

This will have same idea as the `after.sh.erb` used by HPC batch connect apps, the pod won't report as `Running` until the TCP port defined for the pod is actually up.  I tried to make the class structure such that we could switch to a HTTP probe instead of TCP just by adding a new class in the future.  I opted for TCP probe over HTTP probe because didn't want to have to worry about which path for HTTP probe would respond with 200 status code which could vary greatly between batch connect apps.  Using a TCP probe seemed more universal.

Support Kubernetes startupProbe

---

ood_core.gemspec

dont save gh action files. There's no security risk or anything, they just don't need to be distributed.

dont save gh action files

---

lib/ood_core/job/adapters/linux_host/launcher.rb
lib/ood_core/job/adapters/linux_host/templates/script_wrapper.erb.sh
lib/ood_core/version.rb
spec/job/adapters/linux_host/launcher_spec.rb

Fixes #297. Still not working in the browser when trying to launch codeserver, and only codeserver gives the issue.

Lha ssh output crash

---

lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
spec/fixtures/output/k8s/pod_yml_extra_groups.yml
spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
spec/fixtures/output/k8s/pod_yml_from_defaults.yml
spec/fixtures/output/k8s/pod_yml_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_no_init_container.yml
spec/fixtures/output/k8s/pod_yml_no_mounts.yml
spec/fixtures/output/k8s/pod_yml_no_mounts_no_configmaps.yml
spec/fixtures/output/k8s/pod_yml_subpath_configmap.yml

Using Kyverno 1.6.0 pod security standards that mimic Kubernetes pod security standards.  We do have to filter out a few that simply can't support, like we do have to allow hostPath, but these are simple security changes to be able to conform to these new policies.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201901746971618) by [Unito](https://www.unito.io)

Improved pod security

---

spec/job/adapters/slurm_spec.rb

Added extra gpus_from_gres tests for the format:
```
gres/gpu:v100-32g=2
```

Added gpus_from_gres gres/gpu tests

---

lib/ood_core/job/adapters/fujitsu_tcs.rb

This is an adapter for Fujitsu's resource manager, called FUJITSU Software Technical Computing Suite (TCS).
This resource manager is used at the supercomputer Fugaku and several supercomputer centers.
Although the job dependency part is not implemented yet,
I have confirmed that this adapter works with the latest RPM package, ondemand-2.0.27-1 at Fugaku.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671689610771) by [Unito](https://www.unito.io)

Add an adapter for Fujitsu TCS

---

.github/workflows/publish_yarndoc.yml
.gitignore

Fixes #226 by adding a github action to publish the yardocs every push to master.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202701632679248) by [Unito](https://www.unito.io)

publish yardoc pages to gh-pages

---

lib/ood_core/job/adapters/kubernetes/helper.rb

Fixes #744 such that k8s jobs can add as many secrets as they like and we'll read them all back as key value pairs.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203058034806804) by [Unito](https://www.unito.io)

add k8s ability to read many items from secrets

---

lib/ood_core/batch_connect/templates/vnc_container.rb

This pull request adds a new class to the `batch_connect` templates: `vnccontainer`.
This feature was motivated by difficulties running the ANSYS software through Open OnDemand on a Rocky8 cluster at UT Dallas. Since Rocky8 is not an officially supported OS in the ANSYS specs, we had some display issues running ANSYS Workbench through the Open OnDemand desktop. As a solution, we decided to containerize a Centos8 machine--VNC server, xfce4, and all--and run that.
Also, we run a stateless cluster so installing desktops into the chroots really bloats the memory consumption. Containerizing everything solves that issue as well.
`vnccontainer.rb` follows `vnc.rb` closely, but loads a container through `apptainer/singularity instance start`. All VNC and Websockify commands are run in the …

Add template "vnccontainer" for containerized vnc servers

---

lib/ood_core/job/adapters/pbspro.rb
spec/job/adapters/pbspro_spec.rb

Fixes #779 to allow for usernames with periods in them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203168328536059) by [Unito](https://www.unito.io)

fix pbspro to allow for periods in the username

---

lib/ood_core/job/adapters/slurm.rb
spec/fixtures/output/slurm/sacctmgr_show_accts.txt

I've been getting failures around `undefined method `empty?' for nil:NilClass` queue here, so this adds a little safety here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203821081389675) by [Unito](https://www.unito.io)

account for newlines in slurms account api

---

CHANGELOG.md
lib/ood_core/job/adapters/linux_host/launcher.rb
lib/ood_core/version.rb

apptainer regex needs * to pick up all characters, otherwise it's just returning the very first character so folks end up trying to kill pid 3 instead of say pid 301297.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203887738496722) by [Unito](https://www.unito.io)

apptainer regex needs * to pick up all characters

---

lib/ood_core/acl/adapters/group.rb
lib/ood_core/clusters.rb
spec/acl/adapters/group_spec.rb

ACLs to use block & allowlists instead of white & black lists. This is still backward compatible and should be for some time after we update the 2.1 documentation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203923040787317) by [Unito](https://www.unito.io)

ACLs to use block & allowlists

---

lib/ood_core/job/adapters/helper.rb
lib/ood_core/job/adapters/linux_host/launcher.rb
lib/ood_core/job/adapters/systemd/launcher.rb
spec/job/adapters/helper_spec.rb
spec/job/adapters/linux_host/launcher_spec.rb
spec/job/adapters/lsf/batch_spec.rb
spec/job/adapters/pbspro_spec.rb
spec/job/adapters/sge/batch_spec.rb
spec/job/adapters/slurm_spec.rb
spec/job/adapters/torque/batch_spec.rb

Added Functionality to support Non-Standard SSH Port in the Adapters.
The environment variable for ssh port is:  ENV['OOD_SSH_PORT']
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203988635385114) by [Unito](https://www.unito.io)

Added Functionality to support Non-Standard SSH Port in the Adapters.

---

lib/ood_core/job/adapters/kubernetes/batch.rb

Fixes #803 by using the full path for the K8sJobInfo object and throws any errors up the stack because OOD can catch them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204309611557787) by [Unito](https://www.unito.io)

use the full path for k8sjobinfo and throw any errors up the stack

---

lib/ood_core/job/adapters/slurm.rb

Fixes #806
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204364985114375) by [Unito](https://www.unito.io)

fix this if statement for sacctmgr with full path

---

lib/ood_core/batch_connect/template.rb

If all ports in chosen port range were taken, `find_port` had the tendency to block. This fix updates the code to avoid this and instead attempt to find a port by looping over the port range for a fixed number of retries.

find_port: avoid infinite loop

---

lib/ood_core/batch_connect/templates/vnc.rb
lib/ood_core/batch_connect/templates/vnc_container.rb

if `find_port` fails to find a free port, we give up and cleanup. Updating vnc/vnc_container templates accordingly.

handle find_port error codes

---

lib/ood_core/batch_connect/templates/vnc.rb

Instead of running as a daemon, making websockify run as a background process. This ensures that the process gets cleaned up property if and when job is terminated. With certain job schedulers/environments (e.g. OpenPBS+AzHOP), this avoids dangling processes lingering post job termination.

vnc: run websockify as background process

---

lib/ood_core/cluster.rb
spec/cluster_spec.rb

Related to https://github.com/OSC/ondemand/pull/3206 - see specifically https://github.com/OSC/ondemand/pull/3206#discussion_r1406761692

Changes default return value for cluster.batch_connect_ssh_allow?

---

lib/ood_core/batch_connect/templates/vnc_container.rb

Add container_start_args to pass options to the start command.
I'm finding at OSC I need to pass `--fakeroot` to the start command.  This allows for a option to be passed so that users an pass any singularity/apptainer options while starting the container (like `--fakeroot`). 
@georgiastuart FYI

add container_start_args to pass options to the start command

---

lib/ood_core/batch_connect/templates/vnc.rb

Without the --heartbeat option the VNC session will timeout after 1 minute of idle time. This adds --heartbeat with a default of 30 seconds, configurable with websockify_hb in the context or the environment variable WEBSOCKIFY_HB.
This implements the VNC timeout workaround mentioned in 
[VNC timeout](https://discourse.openondemand.org/t/novnc-and-shell-session-timeout-after-1-minute/1622)
The VNC app in OSC/ondemand will need to be updated to recognise the websockify_hb context variable.

Add configurable websocket heartbeat

---

CHANGELOG.md
lib/ood_core/version.rb

bump to next version. @HazelGrant I'd like to get the noVNC heartbeat updates in OOD 3.1.3 as well so we'd need to release this gem and update OOD.

bump to next version

---

lib/ood_core/job/adapter.rb
lib/ood_core/job/adapters/slurm.rb
lib/ood_core/job/node_info.rb
spec/fixtures/output/slurm/owens_nodes.txt
spec/job/adapters/slurm_spec.rb

add a #nodes api to the job adapters so higher level programs like OOD can do things with that information.

add a #nodes api to the job adapters

---

lib/ood_core/job/adapters/slurm.rb
lib/ood_core/job/queue_info.rb
spec/job/adapters/slurm_spec.rb

add gpu awareness to queue_info so upper layers like OOD can make decisions on it.

add gpu awareness to queue_info

---

lib/ood_core/job/adapters/slurm.rb
spec/job/adapters/slurm_spec.rb

The number of active and total GPUs are counted incorrectly because the regular expression searching for GPUs is selecting the wrong number. Fix the regex to select the correct number of GPUs.

Fix GPU Regex

---

ood_core.gemspec

fix ffi dependency for ruby 2.5 and 2.7

fix ffi dependency for ruby 2.5 and 2.7

---

.github/workflows/test.yml

remove support for Ruby 2.5 because OnDemand at this time doesn't support any operating system that uses Ruby 2.5.

remove support for Ruby 2.5

---

lib/ood_core/job/adapters/systemd/launcher.rb

zsh interprets the * in ondemand-* as a file path and returns an error if nothing is matched (unless the user has set 'setopt no_nomatch' in their .zshrc. Escape it to pass the asterisk on to systemctl (so it can be parsed internally).

systemd adapter fails with zsh as user shell

---

.github/workflows/test.yml

add tests for ruby 3.1 and 3.2

add tests for ruby 3.1 and 3.2

---

lib/ood_core/job/adapters/kubernetes/batch.rb

fix ERB.new to remove deprecation warnings.
The warnings in question are these 2:
```
/users/PZS0714/johrstrom/ondemand/misc/core/lib/ood_core/job/adapters/kubernetes/batch.rb:242: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/users/PZS0714/johrstrom/ondemand/misc/core/lib/ood_core/job/adapters/kubernetes/batch.rb:242: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```

fix ERB.new to remove deprecation warnings

---

Rakefile
lib/tasks/slurm.rb

I went to write a test case for squeue in slurm and needed some squeue output to test against. Given that we expect the output to be of a certain format, this was very hard to do by hand.
So I've written this rake task to output 1 single job from squeue -  in the format that this library expects - to write to a fixture file that we can then test against.

add rake task for getting squeue text output

---

.github/workflows/test.yml
Rakefile
ood_core.gemspec
test/job/adapters/slurm_test.rb
test/test_helper.rb

add minitest framework to begin refactoring from rspec.
Fixes #845

add minitest framework

---

lib/ood_core/job/adapters/linux_host/launcher.rb
lib/ood_core/job/adapters/linux_host/templates/script_wrapper.erb.sh

This allows containers launch specs to specify additional options for Singularity such as --nv for nVIDIA GPU and --rocm for AMD GPU or --bind /etc/OpenCL for OpenCL (in combination with one of the prior).
Example:
script:
native:
singularity_bindpath: /tmp,/home,/mnt,/run
singularity_bin: /usr/bin/singularity
singularity_container: "/opt/ood/images/nvidia-parabricks.sif"
singularity_options: "--nv"
Will allow Parabricks to run with nVIDIA GPU.

Add singularity_options to the native structure.

---

lib/ood_core/job/adapters/systemd.rb
lib/ood_core/job/adapters/systemd/launcher.rb

This should give some (albeit poor quality) support for alternative ssh keyfile locations using the systemd launcher.
Our use case is so users don't have to think about ssh key generation etc to reduce a barrier of entry.
I don't write ruby so this is probably a mess.

SSH Keyfile location support for systemd launcher/cluster

---

lib/ood_core/job/adapters/systemd/launcher.rb
test/job/adapters/systemd_launcher_test.rb
test/job/adapters/systemd_test.rb

Small fixup in the logic provided in https://github.com/OSC/ood_core/pull/863 along with some tests for the same feature.

Systemd fixups

---

lib/ood_core/job/adapters/coder.rb
lib/ood_core/job/adapters/coder/batch.rb
lib/ood_core/job/adapters/coder/coder_job_info.rb

This is an adapter for a service called [Coder](https://coder.com/) facilitating OpenStack support, solving the [request for Cloud VM support](https://discourse.openondemand.org/t/cloud-vm-support-openstack/861). It requires both running Coder instance and OpenStack infrastructure. At Metacentrum, we are currently running this version on our development version of OOD, soon moving to produtction. 
You can find more information about this in [my repo](https://github.com/andrejcermak/coder-adapter/) with instructions how to run this extension.

Add working version of OpenStack support

---

lib/ood_core/job/adapters/psij.rb
lib/ood_core/job/adapters/psij/delete.py
lib/ood_core/job/adapters/psij/get_info.py
lib/ood_core/job/adapters/psij/hold.py
lib/ood_core/job/adapters/psij/release.py
lib/ood_core/job/adapters/psij/submit.py
spec/job/adapters/psij_spec.rb

We would like to propose a new adapter to abstract different job schedulers using the Portable Submission Interface for Jobs (PSI/J, https://exaworks.org/psij).
Currently, OOD requires an adapter for each scheduler to be implemented and maintained. To simplify the implementation and reduce maintenance costs, this new adapter allows OOD to interact with different job schedulers through a unified interface using PSI/J.
Since PSI/J currently does not provide hold, release, or info methods, which are necessary for OOD, we are submitting a pull request to PSI/J to implement these methods.
Once this request is approved, we plan to update the documentation with more details.
We would appreciate the opportunity to discuss this pull request first.
Below shows a configuration file to use the …

Abstract job scheduler interface with PSI/J
