OSC/ood_core

- lib/ood_core/job/adapters/slurm.rb
- lib/ood_core/refinements/hash_extensions.rb
- spec/job/adapters/slurm_spec.rb
> Slurm adapter

- CHANGELOG.md
- lib/ood_core/job/adapters/slurm.rb
- lib/ood_core/job/adapters/torque.rb
- lib/ood_core/job/script.rb
- spec/job/adapters/slurm_spec.rb
- spec/job/adapters/torque_spec.rb
- spec/job/script_spec.rb
> Remove join_files

- CHANGELOG.md
- lib/ood_core/job/adapters/slurm.rb
- lib/ood_core/job/adapters/torque.rb
- lib/ood_core/job/script.rb
- spec/job/adapters/slurm_spec.rb
- spec/job/adapters/torque_spec.rb
- spec/job/script_spec.rb
> Remove min_phys_memory

- lib/ood_core/job/adapters/lsf.rb
- lib/ood_core/job/adapters/lsf/batch.rb
- lib/ood_core/job/adapters/lsf/helper.rb
- spec/job/adapters/lsf/helper_spec.rb
- spec/job/adapters/lsf_spec.rb
> Lsf Adapter Updates

- CHANGELOG.md
- lib/ood_core/batch_connect/template.rb
Fixes #55, #56, #57, #58, #59, #60
> Refactored Batch Connect helper functions

- CHANGELOG.md
- lib/ood_core/job/adapters/slurm.rb
- spec/job/adapters/slurm_spec.rb
> Fix bug when parsing nodes in Slurm

- CHANGELOG.md
- lib/ood_core/batch_connect/template.rb
> Fix detection of used port

- CHANGELOG.md
- lib/ood_core/batch_connect/template.rb
> Clean up forked script children

- CHANGELOG.md
- lib/ood_core/job/adapters/lsf/helper.rb
- spec/job/adapters/lsf/helper_spec.rb
> Fix LSF adapter node count

- CHANGELOG.md
- lib/ood_core/job/adapters/lsf.rb
- spec/job/adapters/lsf_spec.rb
> Fix for LSF adapter sometimes returning nil for job info

- lib/ood_core/job/adapters/sge/batch.rb
It ends up that at least in some versions of SGE, SGE_ROOT needs
to be defined in the environment, even if not using libdrmaa.
So for now:
1. Always set SGE_ROOT to the @sge_root string value or ENV['SGE_ROOT'] or a default value.
2. Require explicit path to libdrmaa to be set in order to use libdrmaa.
> Set SGE_ROOT even when libdrmaa is not used

- lib/ood_core/job/adapter.rb
- lib/ood_core/job/adapters/lsf.rb
- lib/ood_core/job/adapters/pbspro.rb
- lib/ood_core/job/adapters/sge.rb
- lib/ood_core/job/adapters/slurm.rb
- lib/ood_core/job/adapters/torque.rb
- spec/job/adapter_spec.rb
- spec/job/adapters/lsf_spec.rb
- spec/job/adapters/pbspro_spec.rb
- spec/job/adapters/sge_spec.rb
- spec/job/adapters/slurm_spec.rb
- spec/job/adapters/torque_spec.rb
This adds the API for a "streaming" approach using iterators and reducing the data load using "filters" on the attributes requested.
> Performance improvements with iterators

- lib/ood_core/job/array_ids.rb
Alternative to https://github.com/OSC/ood_core/pull/146
> Refactor array ids parsing with regex

- .travis.yml
> Update Travis Ruby and Bundle versions to OnDemand's current

- lib/ood_core/job/adapters/linux_host/launcher.rb
- spec/job/adapters/linux_host/launcher_spec.rb
> Add support for using Script#native to specify an override for the submit_host

- lib/ood_core/job/adapters/sge/batch.rb
- spec/job/adapters/sge/batch_spec.rb
> Fix ge nil pathnames

- CHANGELOG.md
- lib/ood_core/version.rb
> update to v0.11.0

- lib/ood_core/job/adapters/linux_host/launcher.rb
- lib/ood_core/job/adapters/linux_host/templates/script_wrapper.erb.sh
Not sure how to write to STDERR so will have to be changed later. Alternative to processing in ruby.
> Process hostnames and ssh_host similarities in bash

- lib/ood_core/job/adapters/slurm.rb
- spec/job/adapters/slurm_spec.rb
Possible fix for #149.
I don't really like using exceptions for control flow, but the way it's structured currently I'm not sure how else to do with without a much more invasive change.
> slurm handle squeue timeouts

- lib/ood_core/job/adapters/ccq.rb
- spec/fixtures/output/ccq/ccqstat
- spec/job/adapters/ccq_spec.rb
> ccq adapter to support jobnames with spaces

- CHANGELOG.md
- lib/ood_core/version.rb
bump version and update changelog for `v0.15.1`.
> bump version and update changelog

- lib/ood_core/job/adapters/kubernetes/batch.rb
- spec/job/adapters/kubernetes/batch_spec.rb
> Save pod yaml into workdir

- lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
- spec/fixtures/output/k8s/pod_yml_no_configmaps.yml
- spec/fixtures/output/k8s/pod_yml_no_mounts_no_configmaps.yml
- spec/job/adapters/kubernetes/batch_spec.rb
> Fix bug in Kubernetes adapter when no configmap is defined

- lib/ood_core/job/adapters/kubernetes/batch.rb
- lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb
- lib/ood_core/job/adapters/slurm.rb
- lib/ood_core/job/adapters/torque.rb
- lib/ood_core/job/script.rb
- spec/fixtures/output/k8s/pod_yml_from_all_configs.yml
- spec/job/adapters/kubernetes/batch_spec.rb
- spec/job/adapters/slurm_spec.rb
- spec/job/adapters/torque_spec.rb
- spec/job/script_spec.rb
> Add gpus_per_node support for SLURM, Torque and Kubernetes

- CHANGELOG.md
> update changelog for v0.17.0

- lib/ood_core/version.rb
:facepalm: we need to remember to update the version when we update the changlog. Not sure how automate this in #285.
> bump version to v0.17.0

- lib/ood_core/job/adapters/kubernetes/helper.rb
- spec/job/adapters/kubernetes/batch_spec.rb
- spec/job/adapters/kubernetes/helper_spec.rb
> Fix K8 where conditions is not defined on pod submission

- lib/ood_core/job/adapters/kubernetes/helper.rb
- spec/fixtures/output/k8s/single_unscheduleable_pod.json
- spec/job/adapters/kubernetes/batch_spec.rb
- spec/job/adapters/kubernetes/helper_spec.rb
> Use pod creation time as one way to get submission time

- lib/ood_core/job/adapters/kubernetes/helper.rb
- spec/fixtures/output/k8s/single_crash_loop_pod.json
- spec/fixtures/output/k8s/single_image_error_pod.json
- spec/job/adapters/kubernetes/helper_spec.rb
> Only show Kubernetes pod as Running when pod is ready

- CHANGELOG.md
- lib/ood_core/version.rb
update changelog for v0.17.2 and bump version
> update changelog for v0.17.2 and bump version

- .github/workflows/publish.yml
Fixes #285 
Fixes #225 
Requires someone add `OSC_RUBYGEMS_API_KEY` secret to OSC organization.
> Add Github action to publish the gem

- .github/workflows/publish.yml
use the osc_robot secret, OSC_RUBYGEMS_API_KEY doesn't exist.
> use the osc_robot secret

- .github/workflows/publish.yml
rake build needs to bundle exec
> rake build needs bundle exec

- lib/ood_core/job/adapters/kubernetes/batch.rb
- spec/job/adapters/kubernetes/batch_spec.rb
Fixes https://github.com/OSC/ondemand/issues/1348
> Do not wait for K8 resources to delete

- CHANGELOG.md
- lib/ood_core/version.rb
update changelog and bump version for v0.17.5
> update changelog and bump version for v0.17.5

- lib/ood_core/version.rb
I almost always forget to bump the version.
> bump version

- .github/workflows/test.yml
- CHANGELOG.md
- lib/ood_core/job/adapters/ccq.rb
- lib/ood_core/job/adapters/kubernetes/batch.rb
- lib/ood_core/job/adapters/kubernetes/helper.rb
- lib/ood_core/job/adapters/kubernetes/k8s_job_info.rb
- lib/ood_core/job/adapters/lsf.rb
- lib/ood_core/job/info.rb
- lib/ood_core/version.rb
- ood_core.gemspec
- spec/job/adapters/ccq_spec.rb
- spec/job/adapters/kubernetes/batch_spec.rb
- spec/job/adapters/kubernetes/helper_spec.rb
- spec/job/adapters/linux_host/launcher_spec.rb
- spec/job/adapters/linux_host_spec.rb
- spec/job/adapters/lsf/batch_spec.rb
- spec/job/adapters/lsf/helper_spec.rb
- spec/job/adapters/lsf_spec.rb
- spec/job/adapters/pbspro_spec.rb
- spec/job/adapters/sge_spec.rb
- spec/job/adapters/slurm_spec.rb
- spec/job/adapters/torque_spec.rb
- spec/job/info_spec.rb
- spec/job/node_info_spec.rb
- spec/job/script_spec.rb
- spec/job/task_status_spec.rb
Fixes #758
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202391223415362) by [Unito](https://www.unito.io)
> Support Ruby 3

- CHANGELOG.md
- lib/ood_core/version.rb
update changelog and bump version
> update changelog and bump version

- lib/ood_core/job/adapters/ccq.rb
- lib/ood_core/job/adapters/kubernetes.rb
- lib/ood_core/job/adapters/kubernetes/batch.rb
- lib/ood_core/job/adapters/kubernetes/helper.rb
- lib/ood_core/job/adapters/kubernetes/k8s_job_info.rb
- lib/ood_core/job/adapters/kubernetes/resources.rb
- lib/ood_core/job/adapters/lsf.rb
- lib/ood_core/job/adapters/sge.rb
- lib/ood_core/job/adapters/sge/helper.rb
- lib/ood_core/job/adapters/sge/qstat_xml_j_r_listener.rb
- lib/ood_core/job/adapters/sge/qstat_xml_r_listener.rb
- lib/ood_core/job/adapters/systemd.rb
- lib/ood_core/job/adapters/torque/attributes.rb
- lib/ood_core/job/adapters/torque/batch.rb
- lib/ood_core/job/adapters/torque/error.rb
- lib/ood_core/job/adapters/torque/ffi.rb
- lib/ood_core/job/array_ids.rb
- lib/ood_core/job/cluster_info.rb
- lib/ood_core/job/info.rb
- lib/ood_core/job/node_info.rb
- lib/ood_core/job/status.rb
Add some class level comments.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202968374679747) by [Unito](https://www.unito.io)
> add some class level comments

- CHANGELOG.md
update changelog for next release
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203271785531003) by [Unito](https://www.unito.io)
> update changelog for next release

- lib/ood_core/version.rb
almost forgot to bump the version here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203272031653154) by [Unito](https://www.unito.io)
> bump version to 0.22.0

- lib/ood_core/job/adapters/linux_host/launcher.rb
Fixes #784.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203716837871738) by [Unito](https://www.unito.io)
> account for apptainer pstree updates

- CHANGELOG.md
- lib/ood_core/version.rb
Bump to the next version when we're ready,
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203759704842915) by [Unito](https://www.unito.io)
> Next version

- lib/ood_core/job/script.rb
Issue #785
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203795894155165) by [Unito](https://www.unito.io)
> aliased queue_name to queue

- lib/ood_core/version.rb
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203994956391396) by [Unito](https://www.unito.io)
> Bump to v0.23.3

- CHANGELOG.md
- lib/ood_core/version.rb
bump to next version
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204334020999838) by [Unito](https://www.unito.io)
> bump to next version

- lib/ood_core/batch_connect/templates/vnc.rb
increase websockify timeout to 10 seconds up from 5.
> increase websockify timeout

- lib/ood_core/batch_connect/templates/vnc.rb
Continuing the work of websockify timeouts, this addition allows ### for variable websockify timeout.
> allow for variable websockify timeout

- lib/ood_core/job/adapters/kubernetes/batch.rb
sanitize k8s namepsaces to fix #852
> sanitize k8s namepsaces

- test/job/adapters/linux_host_test.rb
> add a simple test for the lha

- lib/ood_core/batch_connect/templates/vnc.rb
- lib/ood_core/batch_connect/templates/vnc_container.rb
patch this expression for turbovnc
> patch this expression for turbovnc

- lib/ood_core/version.rb
> bump version to 0.28.0
